name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-release-notes:
    name: Update draft release notes
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
